#!/bin/bash
#----------


FILENAME="`basename ${0}`"
PROTOCOL="https"
HOSTNAME="www.morfix.co.il"
URL="${PROTOCOL}://${HOSTNAME}"
DIV_TAG="normal_translation_div"

# Color output
# ------------
# ANSI escape sequence for yellow color
YELLOW="\e[93m"
# ANSI escape sequence for resetting color
RESET="\e[0m"


if [ $# -eq 0 ]; then
    echo "Usage: ${FILENAME} {insert a word}"
    exit 1
fi

for WORD in "$@"; do

    TRANSLATION=$(curl -s "${PROTOCOL}://${HOSTNAME}/${WORD}" | grep -A1 "${DIV_TAG}" | grep / | cut -d"<" -f1 | head -n 1)

    if [ -z "${TRANSLATION}" ]; then
        echo "Translation not found"
        #exit 1
    else
        #echo -e "${YELLOW}${TRANSLATION}${RESET}"
        echo -e "${YELLOW}${WORD}: \t\t ${TRANSLATION}${RESET}"
    fi
done

# EOF
