#!/bin/bash

echo "______________________________________________________________________________"
echo "### 06. Install JDK17: #######################################################"

echo "Step 1: Installing dependency packge"
sudo apt install libc6-i386 libc6-x32 curl -y
sleep 1

echo "Step 2: Download jdk-17"
curl -O https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
#curl -O https://download.oracle.com/java/17/archive/jdk-17_linux-x64_bin.tar.gz

# If you want to download to a remote server or if you simply prefer wget, use the following command:
# $ wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.oracle.com/ java/17/latest/jdk-17_linux-x64_bin.tar.gz
sleep 1

echo "Step 3: Create directory (jdk/jdk17/) for jdk-17"
mkdir -p jdk/jdk17
sleep 1

echo "Step 4: Extract the jdk-Xxx-linux-xXX.tar.gz file into the jdk/jdk17/ directory"
tar -xvzf jdk-17_linux-x64_bin.tar.gz -C jdk/jdk17/ --strip=1
sleep 1

echo "Step 5: Move the extracted directory into the /opt/ location"
echo "Moving the jdk/jdk-17.{version} directory that include the jdk-17.{version} into /opt/ location"
sudo mv -v jdk/ /opt/
# or
# $sudo mv jdk/ /usr/lib/jvm/jdk17
sleep 1

echo "Step 6: Configure and Install Java 17"
sudo update-alternatives --install "/usr/bin/java" "java" "/opt/jdk/jdk17/bin/java" 0
sudo update-alternatives --install "/usr/bin/javac" "javac" "/opt/jdk/jdk17/bin/javac" 0
# or
# $ sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk17/bin/java" 0
# $ sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk17/bin/javac" 0
sleep 1

echo "Step 7: Step 7: Set the Java and Javac paths in the alternatives system"
sudo update-alternatives --set java /opt/jdk/jdk17/bin/java
sudo update-alternatives --set javac /opt/jdk/jdk17/bin/javac
# or
# $ sudo update-alternatives --set java /usr/lib/jvm/jdk17.0.0/bin/java
# $ sudo update-alternatives --set javac /usr/lib/jvm/jdk17.0.0/bin/javac
sleep 1

echo "Step 8: Verify the setup by listing the Java and Javac alternatives"
update-alternatives --list java
update-alternatives --list javac
sleep 1

echo "Step 9: Set the environment variables"
export JAVA_HOME=/opt/jdk/jdk17
export PATH=$PATH:$JAVA_HOME/bin
# or
# $ export JAVA_HOME=/usr/lib/jvm/jdk17.0.0
# $ export PATH=$PATH:$JAVA_HOME/bin
sleep 1

echo "Step 10: Add the environment variables to /etc/profile or ~/.profile"
echo "Appending the environment variables to ~/.profile"
PROFILE_NAME=~/my.profile
echo "" >> $PROFILE_NAME
echo "# Java 17" >> $PROFILE_NAME
echo 'JAVA_HOME=/opt/jdk/jdk17' >> $PROFILE_NAME
echo 'PATH=$PATH:$HOME/bin:$JAVA_HOME/bin' >> $PROFILE_NAME
echo 'export JAVA_HOME' >> $PROFILE_NAME
echo 'export PATH' >> $PROFILE_NAME

echo "The environment variables added into to the ~/.profile"
echo "The file $PROFILE_NAME was updated!"
sleep 1

echo "Restart the computer (or just log-out and login) and open the terminal again. "
echo "Enter the following command. "
echo ""
echo "Java 17 is now installed. To confirm, use the following commands: "
echo ""
echo "For print export attribute for shell variables. "
echo '$ export -p '
echo ""
echo '$ java --version' 
echo '$ echo $JAVA_HOME'
echo ""
echo "If installed correctly, you should see the following output: "
echo ""
echo "$ java 17 2021-09-14 LTS "
echo "$ Java(TM) SE Runtime Environment (build 17+35-LTS-2724) "
echo "$ Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing) "
echo ""
echo "As you can see, you can see the version is the latest Java 17 JDK build. "
echo
echo "The JDK17 was configured successfuly!"
echo

# Log to file
echo `date +'%F_%T'` $0 runned by $USER >> `date +%F`.log

