#!/bin/bash

echo "_______________________________________________________________________________"
echo "### 01. Install gcc/g++ compiler: #############################################"
sleep 1
echo "Install GCC compiler"
sudo apt install build-essential
echo
sleep 1
