#!/bin/bash


# 01. Enable Root User (Super User):
# ----------------------------------
# 
# If dont work "su -"
# $ su -
# Password:
# su: Authentication failure
# 
# Enable super user account password
# $ sudo passwd root
# [sudo] password for ramesh:
# Enter new UNIX password:
# Retype new UNIX password:
# passwd: password updated successfully


echo "Enable root user (Super User)"
echo "-----------------------------"
echo

su -
echo
sleep 1
