#!/bin/bash


Create Geany launcher and Desktop shortcut:
$ nano ~/Desktop/Geany.desktop
    [Desktop Entry]
    Type=Application
    Version=1.0
    Name=Geany
    GenericName=Integrated Development Environment
    Comment=A fast and lightweight IDE using GTK2
    Exec=geany %F
    Icon=geany
    Terminal=false
    Categories=GTK;Development;IDE;
    MimeType=text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/    x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;appli    cation/xml;text/html;text/css;text/x-sql;text/x-diff;

$ sudo cp ~/Desktop/Geany.desktop /usr/local/share/applications/Geany.desktop
$ sudo cp ~/Desktop/Geany.desktop /usr/share/applications/Geany.desktop

Done!

Run Geany
When programm strarts and did
If you cannot execute build command "xtern -e "/bin/sh/tmp/geany_run_script_xxxx.sh""
Go to
Edit - Preferences - Tools
    Terminal:
        x-terminal-emulator -e "/bin/sh %c"


echo "______________________________________________________________________________"
echo "### 10. Geany IDE: ###########################################################"

$ sudo apt install libgtk-3-dev libgtop2-dev librsvg2-dev
$ sudo apt install intltool

echo "Step 1: Download the Geany IDE"
wget https://download.geany.org/geany-1.38.tar.gz
sleep 1

echo "Step 2: Create directory \'geany/\'"
mkdir geany
sleep 1

echo "Step 3: Extract geany-1.38.tar.gz to geany directory"
tar -xvzf geany-1.38.tar.gz -C geany/ --strip=1
sleep 1

echo "Step 4: Move the extracted archive directory into the /opt/ location"
sudo mv -v geany/ /opt/
sleep 1

echo "Step 5: Create Geany launcher and Desktop shortcut"
echo "        Creating... Geany.desktop file"
touch ~/Desktop/Geany.desktop

echo "        Copying and paste the following block of the text into the Geany.desktop file"

echo "[Desktop Entry]                                " >> ~/Desktop/Geany.desktop
echo "Type=Application                               " >> ~/Desktop/Geany.desktop
echo "Version=1.0                                    " >> ~/Desktop/Geany.desktop
echo "Name=Geany                                     " >> ~/Desktop/Geany.desktop
echo "GenericName=Integrated Development Environment " >> ~/Desktop/Geany.desktop
echo "Comment=A fast and lightweight IDE using GTK2  " >> ~/Desktop/Geany.desktop
echo "Exec=geany %F                                  " >> ~/Desktop/Geany.desktop
echo "Icon=geany                                     " >> ~/Desktop/Geany.desktop
echo "Terminal=false                                 " >> ~/Desktop/Geany.desktop
echo "Categories=GTK;Development;IDE;                " >> ~/Desktop/Geany.desktop
echo "MimeType=text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;   " >> ~/Desktop/Geany.desktop
sleep 1


echo "Step 6: Copy the Shortcut to Applications launcher folder as well"
echo "        $ sudo cp ~/Desktop/Geany.desktop /usr/share/applications/"
echo "        $ sudo cp ~/Desktop/Geany.desktop /usr/local/share/applications/"
sudo cp ~/Desktop/Geany.desktop /usr/share/applications/
sudo cp ~/Desktop/Geany.desktop /usr/local/share/applications/
sleep 1

echo "The Geany IDE was configured successfuly!"
echo
echo "~ Respect! ~"

