#!/bin/bash

#  18 ___________________________________________________________________________________________________
#  19 ##### 02. Install gcc/g++ compiler and some utilities: ############################################
#  20 
#  21 $ sudo apt install build-essential

echo "Install GCC compiler"
sudo apt install build-essential
echo
sleep 1
