#!/bin/bash


echo "______________________________________________________________________________"
echo "### 09. Install Microsoft VSCode: ############################################"

echo "Step 1: Download the Microsoft VSCode"
wget https://az764295.vo.msecnd.net/stable/d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03/code-stable-x64-1644256096.tar.gz
sleep 1

echo "Step 2: Create directory vscode/"
mkdir -p vscode
sleep 1

echo "Step 3: Extract code-stable-x64-1644256096.tar.gz to vscode directory"
tar -xvzf code-stable-x64-1644256096.tar.gz -C vscode --strip=1
sleep 1

echo "Step 4: Move the extracted archive directory into the /opt/ location"
sudo mv -v vscode/ /opt/
sleep 1

echo "Step 5: Create vscode launcher and Desktop shortcut"
echo "        Creating vscode.desktop file"
touch ~/Desktop/vscode.desktop

echo "        Copying and pasting the following block of the text into the vscode.desktop file"

echo "[Desktop Entry]                                        " >  ~/Desktop/vscode.desktop
echo "Version=1.0                                            " >> ~/Desktop/vscode.desktop
echo "Name=vscode                                            " >> ~/Desktop/vscode.desktop
echo "GenericName=vscode                                     " >> ~/Desktop/vscode.desktop
echo "Comment=VSCode IDE                                     " >> ~/Desktop/vscode.desktop
echo "Exec=/opt/vscode/bin/code                              " >> ~/Desktop/vscode.desktop
echo "Icon=/opt/vscode/resources/app/resources/linux/code.png" >> ~/Desktop/vscode.desktop
echo "Terminal=false                                         " >> ~/Desktop/vscode.desktop
echo "Type=Application                                       " >> ~/Desktop/vscode.desktop
sleep 1

echo "Step 6: Copy the Shortcut to Applications launcher folder as well"
echo "        $ sudo cp ~/Desktop/vscode.desktop /usr/share/applications"
echo "        $ sudo cp ~/Desktop/vscode.desktop /usr/local/share/applications/"
sudo cp ~/Desktop/vscode.desktop /usr/share/applications/
sudo cp ~/Desktop/vscode.desktop /usr/local/share/applications/
sleep 1

echo "The VSCode IDE was configured successfuly!"
echo "~ Respect! ~"
echo
