#!/bin/bash

echo "_______________________________________________________________________________"
echo "### 03. Install gcc/g++ compiler: #############################################"
sleep 1
echo "Install GCC compiler"
sudo apt install build-essential
sleep 1
echo "Done!"
