#!/bin/bash

echo "_______________________________________________________________________________"
echo "### 04. Install Python3: ######################################################"

sudo apt install python3-pip
sudo apt install python3-tk

sudo apt install python3 python3-pip python3-tk

echo "check if tkinter works:"
python3 -c "import tkinter"

