#!/bin/bash

echo "_______________________________________________________________________________"
echo "### 04. Install Python3: ######################################################"

echo "Install python3-pip"
sudo apt install python3-pip
sleep 1

echo "Install python3-tk"
sudo apt install python3-tk
sleep 1

#sudo apt install python3 python3-pip python3-tk


# Verify tkinter installation
python3 -c "import tkinter; print('tkinter installed successfully')" 2> /dev/null

if [ $? -ne 0 ]; then
    echo "tkinter installation failed. Please check the installation logs."
else
    echo "Python3 and tkinter installed successfully!"
fi

sleep 1
echo

# Log to file
echo `date +'%F_%T'` $0 runned by $USER >> `date +%F`.log

